config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root "manager/dashboard#index"

  scope module: :manager do
    resources :sub_sub_categories
    resources :sub_categories
    resources :categories
    resources :workers
    resources :dashboard, only: [:index] do
      get :test_page

    end
    resources :appointments do
      member do
        put :approve_appointment
        put :decline_appointment
      end
    end
    resources :staffs
    resources :users   
    resources :divisions 
  end

  namespace :api do
    resources :sessions, only: [:create, :destroy]
    resources :register do
      collection { post :register_device } 
    end
    resources :divisions, only: [:index]
    resources :appointments
    namespace :smartpush_api do
      resources :locations, only: [:create]
    end
  end

  scope module: :smartpush do
    resources :campaigns
    resources :ads
    resources :fences, only: [:index, :create]

  end

  

end

app/controllers/api/appointments_controller.rb
module Api
  class AppointmentsController < Api::BaseController
    
    skip_before_action :authenticate, only: [:create]
    skip_before_filter  :verify_authenticity_token

    before_action :verify_params


    def create
      appointment = Appointment.create(user_id: params[:user_id], detail: params[:details], appointment_date: params[:date], appointment_time: params[:time])
      
      if appointment
        render json: {result: :success}, status: :ok
      else          
        render json: {result: :failur}, :status => 500

      end
    end


    private
    def verify_params
      #TODO      
    end

  end
end

app/controllers/manager/appointments_controller.rb
module Manager
  class AppointmentsController < ApplicationController
    layout 'application'
    before_action :set_appointment, only: [:show, :edit, :update, :destroy]

    # GET /appointments
    # GET /appointments.json
    def index
      @appointments = Appointment.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    end

    # GET /appointments/1
    # GET /appointments/1.json
    def show
    end

    # GET /appointments/new
    def new
      @appointment = Appointment.new
    end

    # GET /appointments/1/edit
    def edit
    end

    # POST /appointments
    # POST /appointments.json
    def create
      @appointment = Appointment.new(appointment_params)

      respond_to do |format|
        if @appointment.save
          format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
          format.json { render :show, status: :created, location: @appointment }
        else
          format.html { render :new }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /appointments/1
    # PATCH/PUT /appointments/1.json
    def update
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
          format.json { render :show, status: :ok, location: @appointment }
        else
          format.html { render :edit }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /appointments/1
    # DELETE /appointments/1.json
    def destroy
      @appointment.destroy
      respond_to do |format|
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def approve_appointment
      id = params[:id]
      appointment = Appointment.find_by_id(id)
      appointment.approved!
      #TODO
      # Send GCM trigger on approve.
      message = appointment.appointment_status(:approved)
      respond_to do |format|
        format.html {redirect_to appointments_path, notice: message}
      end
    end 

    def decline_appointment
      id = params[:id]
      appointment = Appointment.find_by_id(id)
      appointment.declined!
      #TODO
      # Send GCM trigger on approve.
      message = appointment.appointment_status(:declined)
      respond_to do |format|
        format.html {redirect_to appointments_path, notice: message}
      end      
    end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_appointment
        @appointment = Appointment.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def appointment_params
        params.require(:appointment).permit(:category, :appointmnet_date, :appointment_time)
      end
  end
end

app/controllers/manager/categories_controller.rb
module Manager

  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
    end

    # GET /categories/1
    # GET /categories/1.json
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /categories/1
    # PATCH/PUT /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(:title, :description)
      end
  end
end

app/controllers/manager/dashboard_controller.rb
module Manager
  class DashboardController < ApplicationController
  	layout 'application'

	before_action :authenticate_admin!

	  def index

	  end

	def test_page
      
    end

 end
end

app/controllers/manager/divisions_controller.rb
module Manager
	class DivisionsController < ApplicationController
    
    before_action :set_division, only: [:show, :edit, :update, :destroy]
    layout "application"


    def index
      @divisions = Division.all
      @division = Division.new      
    end


    def show
    end

    def new
      @division = Division.new
    end

    def edit
    end

    def create
      @division = Division.new(division_params)

      respond_to do |format|
        if @division.save
          format.html { redirect_to divisions_path, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @division }
        else
          format.html { render :new }
          format.json { render json: @division.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @division.update(division_params)
          format.html { redirect_to divisions_path, notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: @division }
        else
          format.html { render :edit }
          format.json { render json: @division.errors, status: :unprocessable_entity }
        end
      end
    end


    def destroy
      @division.destroy
      respond_to do |format|
        format.html { redirect_to divisions_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_division
        @division = Division.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def division_params
        params.require(:division).permit(:main,:description,:avatar,:for)
      end

	end
end

app/controllers/manager/staffs_controller.rb
module Manager
	class StaffsController < ApplicationController
    
    before_action :set_staff, only: [:show, :edit, :update, :destroy]
    layout "application"


    def index
      @staffs = Staff.all
      @staff = Staff.new      
    end


    def show
    end


    def new
      @staff = Staff.new
    end


    def edit
    end


    def create
      @staff = Staff.new(staff_params)

      respond_to do |format|
        if @staff.save
          format.html { redirect_to staffs_path, notice: 'Staff was successfully created.' }
          format.json { render :show, status: :created, location: @staff }
        else
          format.html { render :new }
          format.json { render json: @staff.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @staff.update(staff_params)
          format.html { redirect_to staffs_path, notice: 'Staff was successfully updated.' }
          format.json { render :show, status: :ok, location: @staff }
        else
          format.html { render :edit }
          format.json { render json: @staff.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @staff.destroy
      respond_to do |format|
        format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_staff
        @staff = Staff.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def staff_params
        params.require(:staff).permit(:first_name, :last_name, :date_of_birth, :description, :age, :email, :phone_number, :address, :status)
      end

	end
end

app/controllers/manager/sub_categories_controller.rb
module Manager
  class SubCategoriesController < ApplicationController
    before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

    # GET /sub_categories
    # GET /sub_categories.json
    def index
      @sub_categories = SubCategory.all
    end

    # GET /sub_categories/1
    # GET /sub_categories/1.json
    def show
    end

    # GET /sub_categories/new
    def new
      @sub_category = SubCategory.new
    end

    # GET /sub_categories/1/edit
    def edit
    end

    # POST /sub_categories
    # POST /sub_categories.json
    def create
      @sub_category = SubCategory.new(sub_category_params)

      respond_to do |format|
        if @sub_category.save
          format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
          format.json { render :show, status: :created, location: @sub_category }
        else
          format.html { render :new }
          format.json { render json: @sub_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /sub_categories/1
    # PATCH/PUT /sub_categories/1.json
    def update
      respond_to do |format|
        if @sub_category.update(sub_category_params)
          format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
          format.json { render :show, status: :ok, location: @sub_category }
        else
          format.html { render :edit }
          format.json { render json: @sub_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /sub_categories/1
    # DELETE /sub_categories/1.json
    def destroy
      @sub_category.destroy
      respond_to do |format|
        format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_sub_category
        @sub_category = SubCategory.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def sub_category_params
        params.require(:sub_category).permit(:title, :description, :category_id)
      end
  end
end

app/controllers/manager/sub_sub_categories_controller.rb
module Manager
  class SubSubCategoriesController < ApplicationController
    before_action :set_sub_sub_category, only: [:show, :edit, :update, :destroy]

    # GET /sub_sub_categories
    # GET /sub_sub_categories.json
    def index
      @sub_sub_categories = SubSubCategory.all
    end

    # GET /sub_sub_categories/1
    # GET /sub_sub_categories/1.json
    def show
    end

    # GET /sub_sub_categories/new
    def new
      @sub_sub_category = SubSubCategory.new
    end

    # GET /sub_sub_categories/1/edit
    def edit
    end

    # POST /sub_sub_categories
    # POST /sub_sub_categories.json
    def create
      @sub_sub_category = SubSubCategory.new(sub_sub_category_params)

      respond_to do |format|
        if @sub_sub_category.save
          format.html { redirect_to @sub_sub_category, notice: 'Sub sub category was successfully created.' }
          format.json { render :show, status: :created, location: @sub_sub_category }
        else
          format.html { render :new }
          format.json { render json: @sub_sub_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /sub_sub_categories/1
    # PATCH/PUT /sub_sub_categories/1.json
    def update
      respond_to do |format|
        if @sub_sub_category.update(sub_sub_category_params)
          format.html { redirect_to @sub_sub_category, notice: 'Sub sub category was successfully updated.' }
          format.json { render :show, status: :ok, location: @sub_sub_category }
        else
          format.html { render :edit }
          format.json { render json: @sub_sub_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /sub_sub_categories/1
    # DELETE /sub_sub_categories/1.json
    def destroy
      @sub_sub_category.destroy
      respond_to do |format|
        format.html { redirect_to sub_sub_categories_url, notice: 'Sub sub category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_sub_sub_category
        @sub_sub_category = SubSubCategory.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def sub_sub_category_params
        params.require(:sub_sub_category).permit(:title, :description, :sub_category_id)
      end
  end
end

app/controllers/manager/users_controller.rb
module Manager
  class UsersController < ApplicationController
    
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    layout "application"


    def index
      @users = User.all
    end


    def show
    end


    def new
      @user = User.new
    end


    def edit
    end

    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @appointment }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to appointments_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :date_of_birth, :gender, :age)
      end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/manager/appointments/index.html.erb
<div class="ibox-content m-b-sm borer-bottom" >
    <div class="p-xs">
        <div class="pull-left m-r-md">
            <i class="fa fa-user fa-5x text-navy mid-icon"></i>
        </div>
        <h2>Appointments</h2>
        <span>Create and manage your users. You can also actviate/deactivate them at any point of time. To view individual users activity please go to the deatils page of individual user.</span>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp ibox-content m-b-sm">

            <div class="ibox">
                <div class="ibox-title">
                    <h5>Appointments</h5>
                </div>
                <div class="ibox-content">
                    <div class="project-list">
                        <table class="table table-hover" id="users_table">
                            <tbody>
                             <% @appointments.each do |appointment| %>
                                <tr id="row_<%= appointment.id %>">

                                    <td><%=appointment.id%></td>
                                    <td><%=appointment.user.nil? ? "" :  appointment.user.first_name%></td>
                                    <td><%=appointment.user.nil? ? "" : appointment.user.email%></td>
                                    <td><%=appointment.appointment_date%></td>
                                    <td><%=appointment.appointment_time.hour.to_s + "h " + appointment.appointment_time.min.to_s + "m" %></td>
                                    <td><span class="label label-info"><%=appointment.status%></span></td>
                                    <td><%= link_to "Approve", approve_appointment_appointment_path(appointment), :class => "btn btn-icon btn-success m-b-5", method: :put, data: { confirm: 'Are you sure?' } %></td>
                                    <td><%= link_to "Decline", decline_appointment_appointment_path(appointment), :class => "btn btn-icon btn-danger m-b-5", method: :put, data: { confirm: 'Are you sure you want to decline appointment ?' } %></td>
                                    <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                                    send message
                                </button></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                        <div class="pagination">
                        <% #will_paginate @users %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal fade" id="myModal6" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Send instant message to user</h4>
            </div>
            <div class="modal-body">
                        <div class="ibox-content">
                            <form class="form-horizontal">
                                <p>Please type in the message to send instantly.</p>
                                <div class="form-group"><label class="col-lg-2 control-label">Title</label>

                                    <div class="col-lg-10"><input type="email" placeholder="Email" class="form-control"> <span class="help-block m-b-none">title block-level help text here.</span>
                                    </div>
                                </div>
                                <div class="form-group"><label class="col-lg-2 control-label">Message</label>

                                    <div class="col-lg-10"><input type="textarea" placeholder="Password" class="form-control"></div>
                                </div>

                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-sm btn-white" type="submit">Send</button>
                                    </div>
                                </div>
                            </form>
                        </div>            

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>




<div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Instant Message</h4>
                <small class="font-bold">Please create teh instant message and push to the users..</small>
            </div>
            <div class="modal-body">
                        <div class="ibox-content">
                            <form class="form-horizontal">
                                <p>Please type in the message to send instantly.</p>
                                <div class="form-group"><label class="col-lg-2 control-label">Title</label>

                                    <div class="col-lg-10"><input type="email" placeholder="title" class="form-control"> <span class="help-block m-b-none"></span>
                                    </div>
                                </div>
                                <div class="form-group"><label class="col-lg-2 control-label">Message</label>

                                    <div class="col-lg-10"><input type="textarea" placeholder="message" class="form-control"></div>
                                </div>
                            </form>
                        </div>            

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</div>