config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root "manager/dashboard#index"

  scope module: :manager do
    resources :sub_sub_categories
    resources :sub_categories
    resources :categories
    resources :workers
    resources :dashboard, only: [:index] do
      get :test_page

    end
    resources :appointments do
      member do
        put :approve_appointment
        put :decline_appointment
      end
    end
    resources :staffs
    resources :users   
    resources :divisions 
  end

  namespace :api do
    resources :sessions, only: [:create, :destroy]
    resources :register do
      collection { post :register_device } 
    end
    resources :divisions, only: [:index]
    resources :appointments
    namespace :smartpush_api do
      resources :locations, only: [:create]
    end
  end

  scope module: :smartpush do
    resources :campaigns
    resources :ads
    resources :fences, only: [:index, :create]

  end

  

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :ads

	# validates_acceptance_of :privacy_policy, :terms_of_service
	validates_length_of :title, within: 5..20
	validates_uniqueness_of :title, message: "%{value} is already registered"
	validates_presence_of :start_date
	validates_presence_of :end_date
	validate :start_date_before_end_date


    private
  
	  def start_date_before_end_date
	  	if self.start_date.present? && self.end_date.present?
		    if self.start_date > self.end_date
		      errors.add(:start_date, "Start date should be before end date")
		    end
		end
	  end
end

app/controllers/smartpush/ads_controller.rb
module Smartpush
  class AdsController < Smartpush::BaseController
    before_action :set_ad, only: [:show, :edit, :update, :destroy]

    # GET /ads
    # GET /ads.json
    def index
      @ads = Ad.all
    end

    # GET /ads/1
    # GET /ads/1.json
    def show
    end

    # GET /ads/new
    def new
      @ad = Ad.new
    end

    # GET /ads/1/edit
    def edit
    end

    # POST /ads
    # POST /ads.json
    def create
      @ad = Ad.new(ad_params)

      respond_to do |format|
        if @ad.save
          format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
          format.json { render :show, status: :created, location: @ad }
        else
          format.html { render :new }
          format.json { render json: @ad.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /ads/1
    # PATCH/PUT /ads/1.json
    def update
      respond_to do |format|
        if @ad.update(ad_params)
          format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
          format.json { render :show, status: :ok, location: @ad }
        else
          format.html { render :edit }
          format.json { render json: @ad.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /ads/1
    # DELETE /ads/1.json
    def destroy
      @ad.destroy
      respond_to do |format|
        format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_ad
        @ad = Ad.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def ad_params
        params.require(:ad).permit(:campaign_id, :title, :description, :type)
      end
  end
end

app/controllers/smartpush/base_controller.rb
module Smartpush
	class BaseController < ApplicationController
		
	end
end

app/controllers/smartpush/campaigns_controller.rb
module Smartpush
  class CampaignsController < Smartpush::BaseController
    before_action :set_campaign, only: [:show, :edit, :update, :destroy]

    # GET /campaigns
    # GET /campaigns.json
    def index
      @campaigns = Campaign.all
    end

    # GET /campaigns/1
    # GET /campaigns/1.json
    def show
    end

    # GET /campaigns/new
    def new
      @campaign = Campaign.new
    end

    # GET /campaigns/1/edit
    def edit
    end

    # POST /campaigns
    # POST /campaigns.json
    def create
      @campaign = Campaign.new(campaign_params)

      respond_to do |format|
        if @campaign.save
          format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
          format.json { render :show, status: :created, location: @campaign }
        else
          format.html { render :new }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /campaigns/1
    # PATCH/PUT /campaigns/1.json
    def update
      respond_to do |format|
        if @campaign.update(campaign_params)
          format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
          format.json { render :show, status: :ok, location: @campaign }
        else
          format.html { render :edit }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /campaigns/1
    # DELETE /campaigns/1.json
    def destroy
      @campaign.destroy
      respond_to do |format|
        format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_campaign
        @campaign = Campaign.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def campaign_params
        params.require(:campaign).permit(:title, :description, :start_date, :end_date, :budget)
      end
  end
end

app/controllers/smartpush/fences_controller.rb
module Smartpush
  class FencesController < Smartpush::BaseController
    layout :false
    skip_before_filter  :verify_authenticity_token
    def index
      
    end

    def create

    fences_array = params[:fences_arr]
    if fences_array != nil
      parsed_fences = parsed = JSON.parse(fences_array)
      logger.info parsed_fences
      
      parsed_fences.each do |fence|
        _lat= fence["lat"]
        _lng= fence["lng"]
        _rad = fence["radius"]

        if Fence.validate_fence(_rad,_lat,_lng) == true
          @fence = Fence.create(ad_id:1,latitude:_lat,longitude:_lng,radius:_rad)
        else
          logger.info "not a valid fence"
        end

      end

    end
      respond_to do |format|
        if @fence.save
          format.html { redirect_to fences_path, notice: 'Ad was successfully created.' }
          format.json { render :show, status: :created, location: @fence }
        else
          format.html { render :new }
          format.json { render json: @fence.errors, status: :unprocessable_entity }
        end
      end

  end

    # # PATCH/PUT /ads/1
    # # PATCH/PUT /ads/1.json
    # def update
    #   respond_to do |format|
    #     if @ad.update(ad_params)
    #       format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
    #       format.json { render :show, status: :ok, location: @ad }
    #     else
    #       format.html { render :edit }
    #       format.json { render json: @ad.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end

    private

      # Never trust parameters from the scary internet, only allow the white list through.
      def ad_params
        params.require(:ad).permit(:ad_id, :latitude, :longitude, :radius)
      end

  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/smartpush/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smartpush/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/smartpush/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.title %></td>
        <td><%= campaign.description %></td>
        <td><%= campaign.start_date %></td>
        <td><%= campaign.end_date %></td>
        <td><%= campaign.budget %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/smartpush/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

app/views/smartpush/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @campaign.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @campaign.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @campaign.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @campaign.end_date %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @campaign.budget %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>