config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root "manager/dashboard#index"

  scope module: :manager do
    resources :sub_sub_categories
    resources :sub_categories
    resources :categories
    resources :workers
    resources :dashboard, only: [:index] do
      get :test_page

    end
    resources :appointments do
      member do
        put :approve_appointment
        put :decline_appointment
      end
    end
    resources :staffs
    resources :users   
    resources :divisions 
  end

  namespace :api do
    resources :sessions, only: [:create, :destroy]
    resources :register do
      collection { post :register_device } 
    end
    resources :divisions, only: [:index]
    resources :appointments
    namespace :smartpush_api do
      resources :locations, only: [:create]
    end
  end

  scope module: :smartpush do
    resources :campaigns
    resources :ads
    resources :fences, only: [:index, :create]

  end

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :campaign
  has_many :fences

  	enum type: ['Notification Ad', 'Banner Ad', 'Fullscreen Ad']


     has_attached_file :ad_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	 validates_attachment_content_type :ad_image, content_type: /\Aimage\/.*\z/

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/apikey.rb
class Apikey < ActiveRecord::Base
  before_validation :generate_token, on: :create
  belongs_to :user
  

  validates :access_token, presence: true, uniqueness: true
  validates_associated :user

  private

  	def generate_token
  		begin
      		self.access_token = SecureRandom.hex
    	end while self.class.exists?(access_token: access_token)
  	end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :user

	enum status: [:pending, :approved, :declined]


	scope :appointments_today, -> { where(:appointment_date => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)) }

	def trigger_appointment_notification

		require 'gcm'
		gcm = GCM.new("AIzaSyDIc9bME_zfUNbKa045xe21sIa6dmFjSC0")
		# you can set option parameters in here
		#  - all options are pass to HTTParty method arguments
		#  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L29-L60
		#  gcm = GCM.new("my_api_key", timeout: 3)

		registration_ids= ["APA91bHfQ6-QbEtcKGCT_eR8XHJ7WQe_mfvGvHIG1qbmEtYD5tD_kKkZvW8NNegqlnO35ZMh3lpyQQxoaplOeCkAAwdEHAtsMd_IGUGrTkYjCBiF0ZUXTAtl2fPGfcEU6Hf8knFMMq04oQIXmu15WMyl_Etm-1PNfg", "13"] # an array of one or more client registration tokens
		options = {data: {score: "123"}, collapse_key: "updated_score"}
		response = gcm.send(registration_ids, options)
		
	end

	def self.schedule_appointments
		require 'gcm'
		gcm = GCM.new("AIzaSyDIc9bME_zfUNbKa045xe21sIa6dmFjSC0")


		today_appointments = Appointment.all.appointments_today
		reg_keys = []

		today_appointments.each do |appointment|

			appointment_hour = 	appointment.appointment_time.hour

			if appointment_hour == (Time.now.hour + 2)
				# puts "Going to send a trigger"

				if !appointment.user.nil?
					if !appointment.user.device.nil?
						reg_keys << appointment.user.device.key
					end
				end
			end
		end

		options = {data: {score: "Your Appointment is coming up!"}, collapse_key: "updated_score"}
		response = gcm.send(reg_keys, options)

	end


	def appointment_status(status)
		
		require 'gcm'
		gcm = GCM.new("AIzaSyDIc9bME_zfUNbKa045xe21sIa6dmFjSC0")

		if status == :approved
			approved_appointment = "Your Appointment is approved for #{self.appointment_date}  at #{self.appointment_time} . See you then!"
			# puts "approved_appointment: " + approved_appointment
			options = {data: {operation_key: :operation_approved_appointment, approved_appointment: approved_appointment }}
		elsif status == :declined
			declined_appointment = "Your Appointment is declined by the admin for #{self.appointment_date} , #{self.appointment_time} ."
			# puts "declined_appointment: " + declined_appointment
			options = {data: {operation_key: :operation_decline_appointment, declined_appointment: declined_appointment }}
		end
		
		if !self.user.device.nil?
			response = gcm.send(self.user.device.key.split(","), options)
			return "user has been notified."
		else
			return "user will be notified shortly."
		end

		# puts "#{self.user.device.key}  ||||| Response: #{response}"
		
	end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :ads

	# validates_acceptance_of :privacy_policy, :terms_of_service
	validates_length_of :title, within: 5..20
	validates_uniqueness_of :title, message: "%{value} is already registered"
	validates_presence_of :start_date
	validates_presence_of :end_date
	validate :start_date_before_end_date


    private
  
	  def start_date_before_end_date
	  	if self.start_date.present? && self.end_date.present?
		    if self.start_date > self.end_date
		      errors.add(:start_date, "Start date should be before end date")
		    end
		end
	  end
end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	validates :key, presence: true
end

app/models/division.rb
class Division < ActiveRecord::Base
	has_many :staff_divisions

	enum main: ["Aromatherapy treatment","Magnolia Hair Treatments","Alfarparf : Intensive hair treatment","Aloe & Protein moisture infusion treatments","Hair Loss Treatment",:hair, :facial, :message, 'Full Body Wax']

	enum for: [:male, :female]

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	def avatar_url_medium
		avatar.url(:medium)
	end

	def avatar_url_thumb
		avatar.url(:thumb)
	end

	def avatar_url_original
		avatar.url()
	end

	def self.trigger_divisions
		require 'gcm'
		gcm = GCM.new("AIzaSyDIc9bME_zfUNbKa045xe21sIa6dmFjSC0")
		# you can set option parameters in here
		#  - all options are pass to HTTParty method arguments
		#  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L29-L60
		#  gcm = GCM.new("my_api_key", timeout: 3)

		registration_ids= ["APA91bHfQ6-QbEtcKGCT_eR8XHJ7WQe_mfvGvHIG1qbmEtYD5tD_kKkZvW8NNegqlnO35ZMh3lpyQQxoaplOeCkAAwdEHAtsMd_IGUGrTkYjCBiF0ZUXTAtl2fPGfcEU6Hf8knFMMq04oQIXmu15WMyl_Etm-1PNfg", "13"] # an array of one or more client registration tokens
		options = {data: {score: "123"}, collapse_key: "updated_score"}
		response = gcm.send(registration_ids, options)
	end

end

app/models/fence.rb
class Fence < ActiveRecord::Base

	belongs_to :ad

  def self.validate_fence(radius,lat,lng)

    if radius.to_f <100 || radius.to_f >10000
      logger.info "not in range"
    return false
    end

    if radius.to_f.is_a?(Numeric) == false
      logger.info "invalid format"
    return false
    end

    if lat.blank? || lng.blank?
      logger.info "blank lat or long"
    return false
    end

    return true
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_many :staff_divisions
end

app/models/staff_division.rb
class StaffDivision < ActiveRecord::Base
	belongs_to :staff
	belongs_to :division
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :sub_sub_categories
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :appointments
	has_one :apikey, dependent: :destroy
	has_one :device, dependent: :destroy
	has_many :locations, dependent: :destroy

end

app/models/worker.rb
class Worker < ActiveRecord::Base
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saloon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
   
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">

        <!-- Navigation starts here  -->

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src= <%= image_url('profile_small.jpg')%> />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><%= current_admin.email%></strong>
                             </span> <span class="text-muted text-xs block">admin profile<b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="#">Profile</a></li>
                                <li><a href="#">Contacts</a></li>
                                <li><a href="#">Mailbox</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            Saloon
                        </div>
                    </li>
                <li>
                    <a href=<%= dashboard_index_path %>><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
                </li>
                <li>
                    <a href=<%=  divisions_path %>><i class="fa fa-plus-circle"></i> <span class="nav-label">Categories</span></a>
                </li>
                <li>
                    <a href=<%= appointments_path %>><i class="fa fa-diamond"></i> <span class="nav-label">Appointments</span></a>
                </li>                
                <li>
                    <a href=<%= users_path %>><i class="fa fa-user"></i> <span class="nav-label">Users</span></a>
                </li> 
                <li>
                    <a href=<%= staffs_path %>><i class="fa fa-users"></i> <span class="nav-label">Staff</span></a>
                </li>                             
                <li>
                    <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">Other</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level hidden" id="myallapps">
                        <li><a href="#">Android App</a></li>
                        <li><a href="#">iOS App</a></li>
                    </ul>
                </li>
                <li class="landing_link">
                    <a href="#"><i class="fa fa-star"></i> <span class="nav-label">Contact US</span></a>
                </li>
                <li class="special_link">
                    <a href="#"><i class="fa fa-file-text"></i> <span class="nav-label">Privacy Policy</span></a>
                </li>


                </ul>

            </div>
        </nav>

        <!-- Navigation ends here -->

        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="http://webapplayers.com/inspinia_admin-v1.8/search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to Saloon admin portal.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="img/a7.jpg">
                                </a>
                                <div class="media-body">
                                    <small class="pull-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="img/a4.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="img/profile.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="profile.html">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="grid_options.html">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <%=link_to "Log out",destroy_admin_session_path, :method => :delete , class: "fa fa-sign-out" %>
                </li>
            </ul>

        </nav>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="wrapper wrapper-content">
                <%= yield %>
                </div>
            </div>
        </div>
            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Example Company &copy; 2014-2015
                </div>
            </div>

        </div>
        </div>

<script type="text/javascript">


    function generate(type, text) {

        var n = noty({
            text        : text,
            type        : type,
            dismissQueue: true,
            layout      : 'topLeft',
            closeWith   : ['click'],
            theme       : 'relax',
            maxVisible  : 10,
            animation   : {
                open  : 'animated bounceInLeft',
                close : 'animated bounceOutLeft',
                easing: 'swing',
                speed : 500
            }
        });
//          console.log('html: ' + n.options.id);
    }

    function generateAll() {
        // generate('warning', notification_html[0]);
        // generate('error', notification_html[1]);
        // generate('information', notification_html[2]);
        // generate('success', notification_html[3]);
//            generate('notification');
//            generate('success');
    }

    $(document).ready(function () {

        setTimeout(function() {
            generateAll();
        }, 500);

    });

    // $("#myallforms").hide();
    // setTimeout(function() { $("#myallforms").show(); }, 5000);


    $(function() {
        // setTimeout() function will be fired after page is loaded
        // it will wait for 5 sec. and then will fire
        // $("#successMessage").hide() function
        setTimeout(function() {
            $('#myallforms').removeClass('hidden');
            $('#myallsubmissions').removeClass('hidden');
            $('#myallapps').removeClass('hidden');

        }, 2000);
    });

</script>




<!-- Noty Test Ends here-->

<% flash.each do |message_type, message| %>
        <%= javascript_tag "generate('#{message_type}', '#{message}')" %>
        <% content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
        

  </body>
</html>